#!/usr/bin/env python3
"""Generate deterministic CLI reference documentation."""

from __future__ import annotations

import argparse
from pathlib import Path

from herdr_orchestrator.cli import build_parser

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "generated" / "cli.md"


def option_name(action: argparse.Action) -> str:
    return ", ".join(action.option_strings) or action.dest


def render() -> str:
    parser = build_parser()
    subcommands = next(
        action for action in parser._actions if isinstance(action, argparse._SubParsersAction)
    )
    lines = [
        "# CLI reference",
        "",
        "<!-- Generated by scripts/generate_reference.py. Do not edit directly. -->",
        "",
        "Run commands from a source checkout with `PYTHONPATH=src uv run python -m "
        "herdr_orchestrator`.",
        "",
    ]
    for name, command in sorted(subcommands.choices.items()):
        lines.extend((f"## `{name}`", "", f"`herdr-orchestrator {name} [arguments]`", ""))
        options = [action for action in command._actions if action.dest != "help"]
        if options:
            lines.extend(("| Argument | Required |", "| --- | --- |"))
            for action in options:
                required = "yes" if getattr(action, "required", False) else "no"
                lines.append(f"| `{option_name(action)}` | {required} |")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("generated CLI reference is stale; run just docs-generate")
            return 1
        print("generated CLI reference: current")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
